### ISSUE TITLE
Support for windows service

### ISSUE THREAD

**Issue by atheinzen** [smartxworks/pySMART#18]
I am interested in running this from a windows service, but any attempt is stopped with "The handle is invalid":

```
Traceback (most recent call last):
  File "lib\site-packages\pySMART\device_list.py", line 52, in __init__
  File "lib\site-packages\pySMART\device_list.py", line 94, in _initialize
  File "lib\site-packages\pySMART\utils.py", line 113, in rescan_device_busses
  File "subprocess.py", line 667, in __init__
  File "subprocess.py", line 890, in _get_handles
OSError: [WinError 6] The handle is invalid
```

After poking around a bit it seems the issue is that windows services do not have a stdin associated. [This question](https://stackoverflow.com/questions/40108816/python-running-as-windows-service-oserror-winerror-6-the-handle-is-invalid) sums up the issue and after some consternation I was able to monkey-patch around the issue by adding `stdin=subprocess.DEVNULL,` but I wonder if there is any plans to support running from a windows service?

**Comment by winkidney** [comment]
Pull Request is always welcome.
Feel sorry for that we have no plan for the purpose of running as windows service.
